spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/petstore}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

flyway:
  enabled: true
  locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

